export const TYPE_COLORS: Record<string, string> = {
  normal: "bg-gray-400",
  fire: "bg-red-500",
  water: "bg-blue-500",
  electric: "bg-yellow-400",
  grass: "bg-green-500",
  ice: "bg-blue-300",
  fighting: "bg-red-700",
  poison: "bg-purple-500",
  ground: "bg-yellow-600",
  flying: "bg-indigo-400",
  psychic: "bg-pink-500",
  bug: "bg-lime-500",
  rock: "bg-yellow-800",
  ghost: "bg-purple-700",
  dragon: "bg-indigo-600",
  steel: "bg-gray-500",
  fairy: "bg-pink-300",
};

export const BG_COLORS: Record<string, string> = {
  normal: "from-gray-100 to-gray-300",
  fire: "from-orange-100 to-orange-200",
  water: "from-blue-100 to-blue-200",
  electric: "from-yellow-100 to-yellow-200",
  grass: "from-green-100 to-green-200",
  ice: "from-cyan-100 to-blue-200",
  fighting: "from-red-100 to-red-200",
  poison: "from-fuchsia-100 to-fuchsia-200",
  ground: "from-amber-100 to-amber-200",
  flying: "from-indigo-100 to-blue-200",
  psychic: "from-pink-100 to-rose-200",
  bug: "from-lime-100 to-lime-200",
  rock: "from-stone-200 to-stone-300",
  ghost: "from-violet-100 to-purple-200",
  dragon: "from-indigo-100 to-violet-200",
  steel: "from-slate-200 to-slate-300",
  fairy: "from-rose-100 to-pink-200",
};

export const TYPE_WEAKNESSES: Record<string, string[]> = {
  normal: ["fighting"],
  fire: ["water", "ground", "rock"],
  water: ["electric", "grass"],
  electric: ["ground"],
  grass: ["fire", "ice", "poison", "flying", "bug"],
  ice: ["fire", "fighting", "rock", "steel"],
  fighting: ["flying", "psychic", "fairy"],
  poison: ["ground", "psychic"],
  ground: ["water", "grass", "ice"],
  flying: ["electric", "ice", "rock"],
  psychic: ["bug", "ghost", "dark"],
  bug: ["fire", "flying", "rock"],
  rock: ["water", "grass", "fighting", "ground", "steel"],
  ghost: ["ghost", "dark"],
  dragon: ["ice", "dragon", "fairy"],
  steel: ["fire", "fighting", "ground"],
  fairy: ["poison", "steel"],
  dark: ["fighting", "bug", "fairy"],
};